### ISSUE TITLE
Can't enter directory made by pupcloud

### ISSUE THREAD

**Issue by mindfuucker** [proofrock/pupcloud#2] opened 2022-04-13 07:47 UTC
Pupcloud: 0.70 - Non Docker

After creating a directory using Pupcloud I cannot seem to enter it. The folder name is added to the path each time I click the directory. Only "Uitzoeken" seems to have this problem.

![image](https://user-images.githubusercontent.com/5075692/163125450-16dc15d4-343e-4d0b-b92a-38209a546cee.png)

What I tried:
- Restarting VM with pupcloud
- Changing permissions to match the other directories 
- Using different browser
- Adding a hello.txt (<--- This fixed the problem!)

![image](https://user-images.githubusercontent.com/5075692/163126138-26c75931-c533-4898-8579-cbfe5304b6df.png)

Edit: It seems like Pupcloud doesn't enter empty directories.

**Comment by proofrock** [comment] 2022-04-13 07:54
The fact that the path is appended "forever" is definitely a bug, thanks for reporting that. Are you able to open the debug console and look at the "network" pane:

![immagine](https://user-images.githubusercontent.com/5470600/163127548-0f9a8b7e-4324-4907-84fb-e3d8baa23972.png)

There should be a call to the service `ls` and if you look at the response it may display an error. If you could report that, it's probably the root cause, we can take a look at it together.

**Comment by proofrock** [comment] 2022-04-13 07:58
Nevermind, I could reproduce it. Issue with JSON serialization, and it's definitely a regression. Will fix ASAP. Thanks!

**Comment by mindfuucker** [comment] 2022-04-13 07:58
Some errors were found: 
![image](https://user-images.githubusercontent.com/5075692/163128172-56c684fa-f919-477f-9a80-88455ed8b3be.png)

The first request seems valid but all subsequent requests fail:
![image](https://user-images.githubusercontent.com/5075692/163128719-d9cd6e00-aed9-49f5-adc0-827634fe1d27.png)

**Comment by proofrock** [comment] 2022-04-13 08:00
Yes, the content gets serialized as `null` but it should be `[]`. Sorry about that.

**Comment by proofrock** [comment] 2022-04-13 08:20
One-liner. If you can compile `develop`, there it is; if not, it will get released within next week. Thanks again!

**Comment by mindfuucker** [comment] 2022-04-13 08:31
I'll just wait for the next release as the "Creating a file in the empty directory " work-around "fixed it" for me.

**Comment by proofrock** [comment] 2022-04-13 08:32
Great! Thanks again.

**Comment by proofrock** [comment] 2022-04-15 19:53
See also #4

**Comment by proofrock** [comment] 2022-04-16 07:54
Released in v0.7.1

**Closed by proofrock** 2022-04-16 07:54 UTC
Labels: bug, fixed-in-branch-develop
