### ISSUE TITLE
Logout icon does not work with subpath reverse proxy

### ISSUE THREAD

**Issue by marioscube** [proofrock/pupcloud#22] opened 2022-05-07 12:01 UTC
I cannot logout
![Screenshot 2022-05-07 at 14 00 14](https://user-images.githubusercontent.com/20281601/167253415-5e5d03b7-de6a-4169-b0b6-5de87faf935a.png)

**Comment by proofrock** [comment] 2022-05-07 12:33
It works for me... there's another bug where the button appears only if you are using a hashed password, but the logout works both in normal and sharing interfaces... what is the behaviour you're observing? What does it do? Nothing at all? What's the OS and browser you're using (on the client side)?

**Comment by marioscube** [comment] 2022-05-07 12:54
I use a hashed password. Don't know why, but why not.

If I log in with 192.168.1.140:17178 the logout icon works

If I login with reverse proxy the login does not work. Screen goes black for < 1 sec (very short) and "start" again.
If I login on share with reverse proxy same behaviour.

Browsers are Firefox 100 and Brave (up to date version) on Mac OS (mojave), hterefore I do not test with Safari

**Comment by proofrock** [comment] 2022-05-07 13:21
So this happens only when using the reverse proxy, right? Shoot. This could be hard to find. Is it the same "subpath" rev proxy, isn't it? I still have to install one :-(

**Comment by marioscube** [comment] 2022-05-07 13:43
Indeed, only if using a reverse proxy (apache2) with a "subpath".

A NGINX reverse proxy might work differently. I've never been able to understand NGINX. If I try to set it up it just does not work a I expect it to, and then I loose interest quite fast.

Apache web server and reverse proxy works for me. 
Just not for a reverse proxy with nextcloud, but let us  not go there ;-( , waaaay beyond the subject of pupcloud.

**Comment by proofrock** [comment] 2022-05-07 13:52
I am way more comfortable with NGINX (in docker, using linuxserver's swag image). Can you link to a good guide to do what you're doing, with apache? I tried yesterday, but I don't even know the name and path of the config file, it's surprisingly confusing.

**Comment by marioscube** [comment] 2022-05-07 14:34
I did a quick search for you, but most "guides" are way to confusing. 

On debian/ubuntu the config files are in /etc/apache2

But something like this? (I hope it works for you, else just ask.)

[as root]
apt install apache2
cd /etc/apache2/sites-available
a2enmod proxy
a2enmon proxy_http
make virthosts.conf file >> nano virthosts.conf

<VirtualHost *:80>

        ServerName 192.168.1.100

        # Reverse Proxy =========================================
        ProxyPreserveHost On
        ProxyRequests off

        <Proxy *>
        Order allow,deny
        Allow from all
        </Proxy>

        ProxyPass /pupcloud http://192.168.1.100:17178
        ProxyPassReverse /pupcloud http://192.168.1.100:17178

       # ========================================================

        ErrorLog ${APACHE_LOG_DIR}/reverseproxy_error.log
        CustomLog ${APACHE_LOG_DIR}/reverseproxy_access.log combined

</VirtualHost> 

save virthosts.conf and then 
a2ensite virthosts.conf
systemctl reload apache2

http://192.16.1.100/pubcloud
should work.

**Comment by proofrock** [comment] 2022-05-07 17:46
Now it's you providing help to me 😄😄😄 thanks a lot for the detailed instructions! I'll try.

**Comment by proofrock** [comment] 2022-05-07 18:08
Ok, perfect instructions thanks! I managed to reproduce the issue. And I really don't know what it is ;-) very interesting.

**Comment by proofrock** [comment] 2022-05-07 18:18
Current code deletes all the cookies from the client, via javascript; this deletes also the authentication cookie, and logs the user out. It seems that this doesn't work from a reverse proxy, it complains about SameSite not being set (though this can be totally unrelated). 

I think I'll do the logout the "safe" way, with a call to the server to invalidate the session. It's also safer after all.

**Comment by marioscube** [comment] 2022-05-07 18:48
Safe is always better, isn’t it?

I have never studied cookies, just try to avoid them. I usually use the “private”  mode of a browser.

**Comment by proofrock** [comment] 2022-05-07 18:57
Cookies are certainly abused, and the "normal" image that we have of them is evil, but they are a very good tool to do a few things that are really necessary (like keeping track of a session, or CRLS protection, that's why I use them). For those use case, the alternative (like using local storage) is even worse. The important thing is not to abuse them. Private mode is OK, because it allows cookies, but limits the misuse of them, which is good.

Anyway, I've done the change, it seems to work. Thanks!

**Comment by proofrock** [comment] 2022-05-07 19:02
Ah, I put a prerelease [here](https://we.tl/t-aSrGxeA2MK) with everything. I think tomorrow afternoon (italian time) I'll release 0.8.0; if you care to try it out before... well, it would be good; but you've done me a great favour already.

**Comment by marioscube** [comment] 2022-05-07 19:37
Uhoh I think you forgot to fix something .....

logout from a reverse proxy-ed shared session.

The env variables are not part of this release right?

**Comment by proofrock** [comment] 2022-05-07 19:40
> The env variables are not part of this release right?

they are, yes

> Uhoh I think you forgot to fix something .....

what??

**Comment by marioscube** [comment] 2022-05-07 19:44
logout from a shared session. 
with and without reverse proxy.

**Comment by proofrock** [comment] 2022-05-07 19:46
uh... as I wrote, it should be solved in commit https://github.com/proofrock/pupcloud/commit/37292de9ae6d8b7b14d8111c88f0100000f36b07 and in the version I put [here](https://we.tl/t-aSrGxeA2MK)

**Comment by marioscube** [comment] 2022-05-07 20:03
Nope, logout from a shared session (with reverse proxy) does not work.

From a regular session with reverse proxy it works.

**Comment by proofrock** [comment] 2022-05-07 20:05
That's very strange, I actually tried. Wait, I'll build a new version with a clear indication of the version number, so that we can be sure that the version is the right one.

**Comment by proofrock** [comment] 2022-05-07 20:11
[https://we.tl/t-4n3d8vSult](https://we.tl/t-4n3d8vSult)

Version 0.8.0RC1, you can check in the footer that appears in the browser for 2 seconds when opening the page.

**Comment by marioscube** [comment] 2022-05-07 20:12
I think that is the problem. I'm working with a version timestamped 20:58

**Comment by proofrock** [comment] 2022-05-07 20:15
Did you download the last one I posted here 3 minutes ago?

**Comment by marioscube** [comment] 2022-05-07 20:23
Yes, and it is rc 8

But no logout from a shared session. (with reverse proxy ant without

**Comment by proofrock** [comment] 2022-05-07 20:27
Omg, from a _shared_ session... I didn't test that. Can you confirm if it works from a _normal_ session?

**Comment by marioscube** [comment] 2022-05-07 20:27
yes, works from a normal session

**Comment by proofrock** [comment] 2022-05-07 20:29
Ok. Tomorrow I will fix the shared case. I am a bit angry with myself for not trying 😒

**Comment by marioscube** [comment] 2022-05-07 20:31
Other problem: for tomorrow

batch file:
#!/bin/bash
PUP_ROOT=/home/user/Share/pubcloud \
./pupcloud

gives error
$ ./pupcloud.sh 
Pupcloud v0.8.0RC1 (c) 2022 Germano Rizzo
ERROR: root dir must exist

Did I do something not right?

**Comment by proofrock** [comment] 2022-05-07 20:37
Simplest questions: does the directory exist? Pubclud with a “b”? And what does ./pupcloud -r /home/user/Share/pubcloud return? The same error, or not?

**Comment by marioscube** [comment] 2022-05-07 20:42
Ahhhhhhhrch. My fingers typt pub when I mean pup every time………

I guess it’s time for some alcohol……

**Comment by proofrock** [comment] 2022-05-07 20:43
Alla tua salute! 🥳

**Comment by proofrock** [comment] 2022-05-07 21:43
[Here the RC2.](https://we.tl/t-INq2ZcBq41) It should work also in sharing mode, now.

**Comment by marioscube** [comment] 2022-05-07 22:11
Problem fixed!

**Comment by proofrock** [comment] 2022-05-08 07:07
Released in v0.8.0

**Comment by proofrock** [comment] 2022-05-08 07:07
Released in v0.8.0

**Closed** 2022-05-08 07:07 UTC
Labels: bug, fixed-in-branch-develop
